### ISSUE TITLE
CQ6 - Workflow running time

### ISSUE THREAD

**Issue by simleo** [ResearchObject/workflow-run-crate#14]
**How long does this workflow take to run?**

The actual duration of the represented workflow run can be obtained from [endTime](http://schema.org/endTime) - [startTime](http://schema.org/startTime) on the `CreateAction`. Providing an estimate of the typical running time, on the other hand, is a different thing. Can we use [totalTime](http://schema.org/totalTime) for that? Or a more specific custom property like `estimatedRunningTime`? And do workflow languages have annotation fields for this?

**Comment by ilveroluca** [comment]
This should probably be "How long *did* this workflow take to run?"  It only seems useful if accompanied by information on the computing infrastructure used for the run.

**Comment by simleo** [comment]
> This should probably be "How long _did_ this workflow take to run?"

The "does" vs "did" here is similar to the discussion on resource usage in #10: "does" implies a prior knowledge from some statistics while "did" is simply a statement of fact regarding the represented run. The answer to the latter is simply to subtract the `startTime` from the `endTime`, so I guess the description for this issue also needs to be clarified.

**Comment by simleo** [comment]
> It only seems useful if accompanied by information on the computing infrastructure used for the run.

Yes, and that's why including a meaningful *estimated* running time is probably too complicated. That would have to refer to an average system, but what exactly is an average system? Even assuming such a system could be identified, its details would have to be included, but it would need to be clear that they refer to a hypotetical system where the workflow is supposed to run in the specified amount of time, and not to the actual system where the run described in the crate took place. The factual information given by `endTime` - `startTime` is sufficient to get an idea of the order of magnitude. I am therefore closing this as the information is already represented in the profiles.
