### ISSUE TITLE
CQ10 - Tool wrappers

### ISSUE THREAD

**Issue by simleo** [ResearchObject/workflow-run-crate#18]
**What is the script used to wrap up a software component?**

We're mapping tool wrappers (e.g., `foo.cwl`) to [SoftwareApplication](http://schema.org/SoftwareApplication). Wrappers at lower levels can also be `SoftwareApplication`, but we need to draw the line somewhere (related to [container image](https://github.com/ResearchObject/workflow-run-crate/issues/9)).

**Comment by stain** [comment]
Would using [softwareRequirements](https://schema.org/softwareRequirements) coupled with `mainEntity` make sense? 

```json
{ "@id": "foo.cwl",
  "@type": "SoftwareApplication",
  "name": "CWL wrapper of Foo",
  "programmingLanguage": {"#cwl"},
  "softwareRequirements": [
      {"@id": "http://example.com/foo"},
      {"@id": "http://python.org/"}
  ],
  "mainEntity": {"@id": "http://example.com/foo"}
},
{
  "@id": "http://example.com/foo",
  "@type": "SoftwareApplication"
}
```

**Comment by kinow** [comment]
Commented in the meeting minutes today, adding here for posterity too. StackStorm allow workflow devs to create Actions for commands, such as `ping`, `docker`, etc.

- https://docs.stackstorm.com/actions.html
- https://number1.co.za/add-a-simple-custom-action-and-action-alias-to-stackstorm/

I think this, and maybe [AirFlow operators](https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/index.html), could serve as options to compare how tool wrappers are used in workflows.

-Bruno

**Comment by simleo** [comment]
As discussed at the 2023-02-16 meeting, in CWL, workflow devs can make things easier by specifying the [SoftwareRequirement hint](https://www.commonwl.org/user_guide/topics/specifying-software-requirements.html), which could be used to fill in `softwareRequirements`. The `mainEntity`, as discussed above, would be harder to determine programmatically, but it's still nice to have it in the model for those cases where it can be filled in.

Note that the "main dependency" would still not provide information on the wrapped executable. For instance, the equivalent of the CWL example linked above would be:

```json
{
    "@id": "interproscan.cwl",
    "@type": "SoftwareApplication",
    "name": "CWL wrapper of InterProScan",
    "softwareRequirements": [
        {"@id": "https://identifiers.org/rrid/RRID:SCR_005829"}
    ],
    "mainEntity": {"@id": "https://identifiers.org/rrid/RRID:SCR_005829"}
},
{
    "@id": "https://identifiers.org/rrid/RRID:SCR_005829",
    "@type": "SoftwareApplication",
    "name": "InterProScan",
    "softwareVersion": "5.21-60"
}
```

Where there's no equivalent of `baseCommand: interproscan.sh`. Also note that some packages install multiple executables.

**Comment by simleo** [comment]
Expected values for [softwareRequirements](https://schema.org/softwareRequirements) are of type [Text](https://schema.org/Text) or [URL](https://schema.org/URL), but not another [SoftwareApplication](https://schema.org/SoftwareApplication). I guess we need to extend the domain via ro-terms.
