### ISSUE TITLE
Representing conditional execution

### ISSUE THREAD

**Issue by simleo** [ResearchObject/workflow-run-crate#33]
How should we model workflows where one or more steps are executed only if a condition is verified (e.g., `when` clause in CWL)?

**Comment by mr-c** [comment]
Sine this RO-Crate profile is about a particular enactment of a workflow, then it might be simpler to not model the condition.

As a bonus, I guess one could record the decision to skip a step. For CWL that would require the CWL document and the input object for that workflow step, then one could investigate the JavaScript statement that was evaluated and found to produce a False (== skip) result. For CWL steps that weren't skipped, the step input object should already be represented allowing a similar analysis post-run of the decision by a human evaluating the JavaScript statement.

**Comment by GlassOfWhiskey** [comment]
This is related to #15. However, there is no `SkippedActionStatus` on [schema.org](https://schema.org/ActionStatusType). Maybe we need another field?

**Comment by stain** [comment]
It depends on the workflow language if conditional execution means the step is run or the datalink is rewired - presumably some evaluation happens though. Is that part of the [ControlAction](https://schema.org/ControlAction) with no tool invocation?

Or would it be an [AssessAction](https://schema.org/AssessAction) that could end up with either subclass [IgnoreAction](https://schema.org/IgnoreAction) or [ChooseAction](https://schema.org/ChooseAction)? Might get quite elaborate as you would then as `object` of those have what was evaluated rather than what inputs were potentially going to be used.

**Comment by simleo** [comment]
StreamFlow is [already using](https://github.com/alpha-unito/streamflow/blob/1ed3ed50e437ffa81d5a8976258057c779f956e2/streamflow/provenance/run_crate.py#L68) `PotentialActionStatus`

**Comment by simleo** [comment]
In CWLProv, skipped actions are not recorded. Hence, in `runcrate convert`, the tool / subworkflow is listed in the prospective provenance but there is no corresponding action in the retrospective provenance. See https://github.com/ResearchObject/runcrate/pull/45, which adds an example where a subworkflow is skipped.

**Comment by simleo** [comment]
> StreamFlow is [already using](https://github.com/alpha-unito/streamflow/blob/1ed3ed50e437ffa81d5a8976258057c779f956e2/streamflow/provenance/run_crate.py#L68) `PotentialActionStatus`

I ran the workflow used to test https://github.com/ResearchObject/runcrate/pull/45 with Streamflow (0.2.0.dev5) and generated the RO-Crate: it turns out that it **does not** add an action with `PotentialActionStatus`. Instead, it behaves like runcrate after the merging of https://github.com/ResearchObject/runcrate/pull/45 (subworkflow and step are listed, but no corresponding action).

**Comment by stain** [comment]
TRE-FX also have execution states  https://trefx.uk/5s-crate/0.4/#execution-states - but for the overall workflow.  e.g. http://schema.org/ActiveActionStatus  if it's still running.  In theory if someone was doing similar execution steps for a workflow that is not yet finished, then some of those would be in PotentialActionStatus until it's not executed.  You would need to add something like a https://schema.org/IgnoreAction control action show that the step was later NOT picked so it would get complicated. So I would support #70 for its simplicity.
